// src/app/view/paciente/carnet/carnet.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';

export interface CarnetElement {
  fecha_prescripcion: string;
  id_prescripcion: string;
  generico: string;
  consumo: string;
  cantidad_bolos: string;
  entregado: string;
}

let ELEMENT_DATA: CarnetElement[] = [];

@Component({
  selector: 'app-carnet',
  templateUrl: './carnet.component.html',
  styleUrls: ['./carnet.component.scss']
})

export class CarnetComponent implements OnInit {
  searchForm: FormGroup;
  nssPdf: any;
  arraySesiones: any[] = [];
  showIndex = false;
  pacientes = [];
  paciente = null;
  pacienteHistoria = [];
  dataSource = ELEMENT_DATA;
  displayedColumns: string[] = ['fecha_prescripcion', 'id_prescripcion', 'generico', 'consumo', 'cantidad_bolos', 'entregado'];
  constructor(
    private formBuilder: FormBuilder,
    private toastr: ToastrService,
  ) { }

  ngOnInit(): void {
    this.initForms();
  }

  initForms() {
    this.searchForm = this.formBuilder.group({
      curpPaciente: ['', Validators.required],
      nnsPaciente: ['', Validators.required],
      unidadMedicaPaciente: ['', Validators.required],
      nombrePaciente: ['', Validators.required],
      apellidoPaternoPaciente: ['', Validators.required],
      apellidoMaternoPaciente: ['', Validators.required],
    });
  }

  limpiar() {
    this.searchForm.controls['curpPaciente'].setValue('');
    this.searchForm.controls['nnsPaciente'].setValue('');
    this.searchForm.controls['unidadMedicaPaciente'].setValue('');
    this.searchForm.controls['nombrePaciente'].setValue('');
    this.searchForm.controls['apellidoPaternoPaciente'].setValue('');
    this.searchForm.controls['apellidoMaternoPaciente'].setValue('');
    this.paciente = null;
    this.pacientes = [];
  }

  searchByNss() {
    const url = `http://10.100.6.97/api/v1/resources/padrones?nss=${this.searchForm.controls['nnsPaciente'].value}&curp=${this.searchForm.controls['curpPaciente'].value}&nombre_paciente=${this.searchForm.controls['nombrePaciente'].value}&ap_paterno_paciente=${this.searchForm.controls['apellidoPaternoPaciente'].value}&ap_materno_paciente=${this.searchForm.controls['apellidoMaternoPaciente'].value}&unidad_medica_atencion=${this.searchForm.controls['unidadMedicaPaciente'].value}`
    fetch(url)
      .then(response => response.json())
      .then(data => {
        this.pacientes = data.map((value) => {
          return value._id;
        });
      })
      .catch(error => this.toastr.error(error))
  }

  asignarPaciente(paciente) {
    this.paciente = paciente;
    this.pacientes = [];
    const url = `http://10.100.6.97/api/v1/resources/carnets?nss=${paciente.nss}`;
    fetch(url)
      .then(response => response.json())
      .then(async data => {
        // console.log(data)
        this.dataSource = await data.map((value) => {
          value.fecha_prescripcion = value.fecha_prescripcion.$date;
          return value;
        });
        this.paciente.edad = data[0].edad;
        this.paciente.fecha_nacimiento = data[0].fecha_nacimiento;
        this.paciente.peso = data[0].peso;
        this.paciente.agregado_medico = data[0].agregado_medico;
        this.paciente.diagnostico = data[0].diagnostico;
        this.paciente.tipo_mezcla = data[0].tipo_mezcla;
        function groupBy(collection, property) {
          let i = 0, val, index, values = [], result = [];
          for (; i < collection.length; i++) {
            if (collection[i]['generico'] != 'Jeringas'){
              val = collection[i][property];
              index = values.indexOf(val);
              if (index > -1) result[index].push(collection[i]);
              else {
                values.push(val);
                result.push([collection[i]]);
              }
            }
          }
          return result;
        }
        this.pacienteHistoria = groupBy(data, 'fecha_prescripcion');
        console.log(this.pacienteHistoria)
        // this.dataSource = data.map((value) => {
        //   return {
        //     fecha_prescripcion: value.fecha_prescripcion,
        //     id_prescripcion: value.id_prescripcion,
        //     generico: value.generico,
        //     consnumo: value.consumo,
        //     cantidad_bolos: value.cantidad_bolos,
        //     entregado: value.entregado
        //   };
        // });
      })
      .catch(error => this.toastr.error(error));
  }
}

<h4 class="h4">Carnet</h4>
<hr class="red" />
<!-- tabla de pacientes -->
<form [formGroup]="searchForm">
    <div class="row form">
      <div class="col-sm-12">
        <p>INGRESA LOS DATOS DEL PACIENTE</p>
      </div>
    </div>
    <div class="row form">
        <div class="col-sm-4">
            <div class="form-group datepicker-group">
                <label class="control-label" for="curpPaciente">CURP:</label>
                <input class="form-control" type="text" placeholder="" formControlName="curpPaciente" />
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group datepicker-group">
                <label class="control-label" for="nnsPaciente">Numero de seguridad social:</label>
                <input class="form-control" id="nnsPaciente" type="text" placeholder="" formControlName="nnsPaciente" />
                <span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>
            </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group datepicker-group">
            <label class="control-label" for="unidadMedicaPaciente">Unidad medica:</label>
            <input class="form-control" type="text" placeholder="" formControlName="unidadMedicaPaciente" />
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
          </div>
        </div>
    </div>
    <div class="row form">
      <div class="col-sm-4">
        <div class="form-group datepicker-group">
          <label class="control-label" for="nombrePaciente">Nombre(s):</label>
          <input class="form-control" type="text" placeholder="" formControlName="nombrePaciente" />
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group datepicker-group">
          <label class="control-label" for="apellidoPaternoPaciente">Apellido Paterno</label>
          <input class="form-control" id="apellidoPaternoPaciente" type="text" placeholder="" formControlName="apellidoPaternoPaciente" />
          <span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group datepicker-group">
          <label class="control-label" for="apellidoMaternoPaciente">Apellido Materno</label>
          <input class="form-control" type="text" placeholder="" formControlName="apellidoMaternoPaciente" />
          <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </div>
      </div>
    </div>
    <div class="row form" style="margin-top: 2rem; margin-bottom: 5rem;">
      <div class="col-sm-4">
        <button (click)="limpiar()" class="btn ml-0" type="button">Limpiar</button>
        <button (click)="searchByNss()" [disabled]="false" class="btn btn-primary" type="button">Buscar</button>
      </div>
    </div>
</form>

<ng-container *ngIf="(pacientes.length > 0)">
  <h4 class="title col-12">Pacientes encontrados</h4>
  <table class="table table-bordered table-striped col-12">
    <thead>
      <tr>
        <th>NSS</th>
        <th>CURP</th>
        <th>Nombre</th>
      </tr>
    </thead>
    <tbody>
      <!-- ngFor del objeto de nucleo -->
      <tr *ngFor="let item of pacientes" (click)="asignarPaciente(item)">
        <th>{{item.nss ? item.nss : '-'}}</th>
        <th>{{item.curp ? item.curp : '-'}}</th>
        <th>{{item.nombre_paciente}} {{item.ap_paterno_paciente}} {{item.ap_materno_paciente}}</th>
      </tr>
    </tbody>
  </table>
</ng-container>

<!-- carnet -->
<ng-container *ngIf="pacienteHistoria.length > 1">
  <div class="form">
    <div class="title col-sm-12 bordet-b m-0 p-1 head-carnet" style="margin-left: 0.2%;">
      <div class="col-md-5 text-left">
        <p style="margin-bottom: 1.5rem!important;"><strong>Nombre:</strong><br />{{paciente.nombre_paciente}}, {{paciente.ap_paterno_paciente}} {{paciente.ap_materno_paciente}}</p>
        <br />
        <p style="margin-bottom: 1.5rem!important;"><strong>CURP:</strong><br />{{paciente.curp}}</p>
        <br />
        <p style="margin-bottom: 1.5rem!important;"><strong>NSS:</strong><br />{{paciente.nss}}</p>
        <br />
        <p style="margin-bottom: 1.5rem!important;"><strong>Edad:</strong><br />{{paciente.edad}} años</p>
      </div>
      <div class="col-md-4 text-left">
        <p style="margin-bottom: 1.5rem!important;"><strong>Fecha de nacimiento:</strong><br />{{paciente.fecha_nacimiento.$date| date}}</p>
        <br />
        <p style="margin-bottom: 1.5rem!important;"><strong>Agregado Médico:</strong><br />{{paciente.agregado_medico}}</p>
        <br />
        <p style="margin-bottom: 1.5rem!important;"><strong>Peso:</strong><br />{{paciente.peso}} Kg</p>
      </div>
      <div class="col-md-3 " style="position:absolute; bottom:0; right:0;">
        <img src="assets/img/carnet_img.png" width="100%" height="100%" />
      </div>
    </div>
  </div>
  <mat-expansion-panel hideToggle *ngFor="let historia of pacienteHistoria" style="margin-top: 2rem; margin-bottom: 2rem;">
    <mat-expansion-panel-header style="background-color: rgb(246 246 246);">
      <mat-panel-title>
        Unidad de atención:<br/>
        {{historia[0].unidad_medica_atencion}}
      </mat-panel-title>
      <mat-panel-description>
        Doctor (a):<br />
        {{historia[0].medico}}
      </mat-panel-description>
      <mat-panel-description>
        Cama:<br />
        {{historia[0].cama ? historia[0].cama : '-'}}
      </mat-panel-description>
      <mat-panel-description>
        Fecha:<br />
        {{historia[0].fecha_prescripcion | date}}
      </mat-panel-description>
    </mat-expansion-panel-header>
    <table mat-table [dataSource]="historia" class="mat-elevation-z8" style="min-width: 100%;">
      <!--- Note that these columns can be defined in any order.
            The actual rendered columns are set as a property on the row definition" -->
      <!-- Position Column -->
      <ng-container matColumnDef="fecha_prescripcion">
        <th mat-header-cell *matHeaderCellDef> Fecha de prescripcion </th>
        <td mat-cell *matCellDef="let item"> {{item.fecha_prescripcion | date}} </td>
      </ng-container>
      <!-- Name Column -->
      <ng-container matColumnDef="id_prescripcion">
        <th mat-header-cell *matHeaderCellDef> Id prescripción </th>
        <td mat-cell *matCellDef="let item"> {{item.id_prescripcion}} </td>
      </ng-container>
      <!-- Weight Column -->
      <ng-container matColumnDef="generico">
        <th mat-header-cell *matHeaderCellDef> Genérico </th>
        <td mat-cell *matCellDef="let item"> {{item.generico}} </td>
      </ng-container>
      <!-- Symbol Column -->
      <ng-container matColumnDef="consumo">
        <th mat-header-cell *matHeaderCellDef> Consumo </th>
        <td mat-cell *matCellDef="let item"> {{item.consumo}} {{item.unidad_medida}}</td>
      </ng-container>
      <!-- Symbol Column -->
      <ng-container matColumnDef="cantidad_bolos">
        <th mat-header-cell *matHeaderCellDef> Cantidad </th>
        <td mat-cell *matCellDef="let item"> {{item.cantidad_bolos}} </td>
      </ng-container>
      <!-- Symbol Column -->
      <ng-container matColumnDef="entregado">
        <th mat-header-cell *matHeaderCellDef> Entregado </th>
        <td mat-cell *matCellDef="let item"> {{item.entregado}} <small class="color:red">{{item.motivo}}</small> </td>
      </ng-container>
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
    </table>
  </mat-expansion-panel>
</ng-container>

// src/view/pages/carnet/Carnet.vue
<template lang="pug">
  div
    .row.q-py-md.q-px-xl
      .col
        span.text-h4 Carnet
        q-separator(color='secondary' size='2px')
        q-separator.q-mb-md(color='secondary' size='.5rem' style='max-width:2.5rem')
        q-form
          p INGRESA LOS DATOS DEL PACIENTE
          .row.q-gutter-md
            .col
              q-input(
                  outlined=''
                  dense=''
                  v-model='form.curp'
                  label='CURP'
                  lazy-rules=''
                )
                  template(v-slot:append='')
                    q-icon(name='assignment_ind')
            .col
              q-input(
                  outlined=''
                  dense=''
                  v-model='form.nss'
                  label='Numero de seguridad social'
                  lazy-rules=''
                )
                  template(v-slot:append='')
                    q-icon(name='contact_mail')
            .col
              q-input(
                  outlined=''
                  dense=''
                  v-model='form.unidad_medica_atencion'
                  label='Unidad Médica'
                  lazy-rules=''
                )
                  template(v-slot:append='')
                    q-icon(name='local_pharmacy')
          .row.q-gutter-md.q-mt-sm
            .col
              q-input(
                  outlined=''
                  dense=''
                  v-model='form.nombre_paciente'
                  label='Nombre del paciente'
                  lazy-rules=''
                )
                  template(v-slot:append='')
                    q-icon(name='contacts')
            .col
              q-input(
                  outlined=''
                  dense=''
                  v-model='form.ap_paterno_paciente'
                  label='Apellido paterno'
                  lazy-rules=''
                )
                  template(v-slot:append='')
                    q-icon(name='contacts')
            .col
              q-input(
                  outlined=''
                  dense=''
                  v-model='form.ap_materno_paciente'
                  label='Apellido materno'
                  lazy-rules=''
                )
                  template(v-slot:append='')
                    q-icon(name='contacts')
          div.q-mt-md
            q-btn(
              :loading='searching'
              color='primary'
              outline=''
              ref='searchPatient'
              @click='search'
              style='min-width: 160px'
            )
              | {{pacientes.length === 0 ? "Buscar paciente" : "Buscar otro paciente"}}
              template(v-slot:loading='')
                q-spinner-hourglass.on-left
                | Buscando...
            q-btn.q-ml-sm(
              label='Limpiar'
              color='secondary'
              flat=''
              @click='reset'
            )
    .row.q-px-xl.q-mb-xl
      .col
        template
          q-banner.bg-warning.text-center.alert-banner.q-mb-md(
            inline-actions=''
            rounded=''
            dense=''
            v-if='!paciente'
          )
            span {{pacientes.length ? `${pacientes.length} Pacientes encontrados` : 'Busca un paciente para ver los resultados'}}
          q-table(
            v-if='pacientes.length'
            :data='pacientes'
            :columns='columns'
            row-key='name'
            flat=''
            bordered=false
            :dense='$q.screen.lt.md'
            :rows-per-page-options='[10, 25, 50, 100, 200]'
            rows-per-page-label='Pacientes por página'
          )
            template(v-slot:body-cell='props')
              q-td.cursor-pointer(:props='props' @click='setPatient(props.row)')
                span(v-if="props.col.field === 'nombre_paciente'") {{props.value}} {{props.row.ap_paterno_paciente}} {{props.row.ap_materno_paciente}}
                span(v-else-if="props.col.field === 'edad'") {{props.value}} años
                span(v-else-if="props.col.field === 'actions'")
                  q-icon(name='person_search' size='md', color='accent')
                span(v-else) {{props.value}}
        template(v-if="paciente")
          q-banner.text-center.alert-banner.alert-img-carnet.q-mb-md.q-py-lg.q-px-xl(
            inline-actions=''
            rounded=''
            dense=''
          )
            .row
              .col.text-left
                span.text-weight-bold Nombre:
                br
                span {{paciente.nombre_paciente}} {{paciente.ap_paterno_paciente}} {{paciente.ap_materno_paciente}}
              .col.text-left
                span.text-weight-bold CURP:
                br
                span {{paciente.curp}}
              .col.text-left
                span.text-weight-bold NSS:
                br
                span {{paciente.nss}}
            .row.q-mt-md
              .col.text-left
                span.text-weight-bold Fecha de nacimiento:
                br
                span {{paciente.fecha_nacimiento.$date | DateTime}}
              .col.text-left
                span.text-weight-bold Edad:
                br
                span {{paciente.edad}} años
              .col.text-left
                span.text-weight-bold Peso:
                br
                span {{paciente.peso}} Kg
            .row.q-mt-md
              .col.text-left
                span.text-weight-bold Agregado médico:
                br
                span {{paciente.agregado_medico}}
              .col.text-left
              .col.text-left
          q-banner.text-center.no-padding.q-mb-md(
            inline-actions=''
            rounded=''
            dense=''
          )
            .row.bg-grey-2.q-py-sm
              .col
                span.text-weight-bold.text-center DIAGNOSTICO
              .col
                span.text-weight-bold.text-center INFORMACIÓN
            .row.bg-grey-4.q-py-sm
              .col
                span.text-center {{paciente.diagnostico_cie10}}
              .col
                span.text-center Tipo mezcla: {{paciente.tipo_mezcla}}
          q-list.q-mb-md(
            bordered=''
            v-for='(carnet, i) in carnets'
            :key='i'
          )
            q-expansion-item.bg-grey-2(
              group='somegroup'
              icon='explore'
            )
              template(v-slot:header='')
                .col
                  q-item-section
                    p.no-margin Unidad de atención
                    p.no-margin.text-weight-bold {{carnet.unidad_medica_atencion ? carnet.unidad_medica_atencion : '-'}}
                .col
                  q-item-section
                    p.no-margin Médico
                    p.no-margin.text-weight-bold {{carnet.medico ? carnet.medico : '-'}}
                .col
                  q-item-section
                    p.no-margin Cama
                    p.no-margin.text-weight-bold {{carnet.cama ? carnet.cama : '-'}}
                .col
                  q-item-section
                    p.no-margin Fecha de la cita
                    p.no-margin.text-weight-bold {{carnet.fecha_prescripcion.$date ? carnet.fecha_prescripcion.$date : null | DateTime}}
              q-markup-table(flat='' bordered=false)
                thead
                  tr
                    th.text-center Genérico
                    th.text-center Consumo
                    th.text-center Cantidad
                    th.text-center Entregado
                tbody
                  tr(v-for='(prescription, p) in carnet.carnet', :key='p')
                    td.text-center {{prescription.generico}}
                    td.text-center {{prescription.consumo}} {{prescription.unidad_medida}}
                    td.text-center {{prescription.cantidad_bolos}}
                    td.text-center
                      q-icon(
                        :color='prescription.entregado === "ENTREGADO" ? "positive" : "negative"'
                        :name='prescription.entregado === "ENTREGADO" ? "done" : "clear"'
                      )
                      span(
                        :color='prescription.entregado === "ENTREGADO" ? "" : "negative"'
                      ) {{prescription.motivo}}

</template>

<script>
import ApiMongoService from '@/boot/services/api.mongo.service'
import { GETPATIENTS, CARNET } from '@/boot/endpoints/carnet'
export default {
  data () {
    return {
      searching: false,
      form: {
        curp: '',
        nss: '',
        unidad_medica_atencion: '',
        nombre_paciente: '',
        ap_paterno_paciente: '',
        ap_materno_paciente: ''
      },
      columns: [
        { label: 'NSS', field: 'nss', align: 'left' },
        { label: 'CURP', field: 'curp', align: 'left' },
        { label: 'Nombre', field: 'nombre_paciente', align: 'left' },
        { label: 'Edad', field: 'edad', align: 'left' },
        { label: 'Diagnostico', field: 'diagnostico_cie10', align: 'left' },
        { label: 'Acciones', field: 'actions', align: 'left' }
      ],
      pacientes: [],
      paciente: null,
      carnets: []
    }
  },
  methods: {
    search () {
      this.paciente = null
      this.searching = true
      ApiMongoService.get(GETPATIENTS, this.form)
        .then(response => response.json())
        .then(data => {
          this.pacientes = data
        })
        .finally(() => { this.searching = false })
    },
    setPatient (patient) {
      this.pacientes = {}
      ApiMongoService.get(CARNET, patient)
        .then(response => response.json())
        .then((data) => {
          console.log(data)
          this.paciente = data[0]
          this.carnets = data
        })
    },
    reset () {
      // this.form = {
      //   curp: '',
      //   nns: '',
      //   unidad_medica_atencion: '',
      //   nombre_paciente: '',
      //   ap_paterno_paciente: '',
      //   ap_materno_paciente: ''
      // }
      this.pacientes = []
      this.paciente = null
      this.carnets = []
    }
  }
}
</script>

<style lang="sass" scoped>
.alert-banner
  background-color: #fcf2ce!important
  border-color: $warning!important
.alert-img-carnet
  background-image: url(~assets/img/carnet/carnet.png);
  background-position: top right 10%;
  background-size: contain;
  background-repeat: no-repeat;
</style>
